from unittest import TestCase
from task08 import SimpleGraph
from task08_2 import DirectedGraph

class TestHeap(TestCase):
    def test_AddVertex(self):
        graph: SimpleGraph = SimpleGraph(3)
        for val in graph.vertex:
            self.assertIsNone(val)
        graph.AddVertex(10)
        self.assertEqual(10, graph.vertex[0].Value)
        self.assertIsNone(graph.vertex[1])
        self.assertIsNone(graph.vertex[2])
        for i in range(graph.max_vertex):
            self.assertEqual(0, graph.m_adjacency[0][i])
            self.assertEqual(0, graph.m_adjacency[i][0])
        graph.AddVertex(11)
        self.assertEqual(10, graph.vertex[0].Value)
        self.assertEqual(11, graph.vertex[1].Value)
        self.assertIsNone(graph.vertex[2])
        for i in range(graph.max_vertex):
            self.assertEqual(0, graph.m_adjacency[1][i])
            self.assertEqual(0, graph.m_adjacency[i][1])
        graph.AddVertex(12)
        self.assertEqual(10, graph.vertex[0].Value)
        self.assertEqual(11, graph.vertex[1].Value)
        self.assertEqual(12, graph.vertex[2].Value)
        for i in range(graph.max_vertex):
            self.assertEqual(0, graph.m_adjacency[2][i])
            self.assertEqual(0, graph.m_adjacency[i][2])

    def test_AddEdge(self):
        graph: SimpleGraph = SimpleGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertEqual(0, graph.m_adjacency[1][2])
        self.assertEqual(0, graph.m_adjacency[2][1])
        graph.AddEdge(1, 2)
        self.assertEqual(1, graph.m_adjacency[1][2])
        self.assertEqual(1, graph.m_adjacency[2][1])

        self.assertEqual(0, graph.m_adjacency[0][0])
        graph.AddEdge(0, 0)
        self.assertEqual(1, graph.m_adjacency[0][0])

    def test_IsEdge(self):
        graph: SimpleGraph = SimpleGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertFalse(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertFalse(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(1, 2)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(0, 0)
        self.assertTrue(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

    def test_RemoveEdge(self):
        graph: SimpleGraph = SimpleGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertFalse(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertFalse(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(1, 2)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(0, 0)
        self.assertTrue(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

        graph.RemoveEdge(0, 0)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

        graph.RemoveEdge(1, 0)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

        graph.RemoveEdge(2, 1)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertFalse(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertFalse(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

    def test_RemoveVertex(self):
        graph: SimpleGraph = SimpleGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        graph.AddEdge(1, 2)
        graph.AddEdge(1, 0)
        graph.AddEdge(1, 1)
        graph.AddEdge(2, 0)
        graph.RemoveVertex(1)
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertFalse(graph.IsEdge(1, 2))
        self.assertTrue(graph.IsEdge(0, 2))

    def test_Directed_AddEdge(self):
        graph: DirectedGraph = DirectedGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertEqual(0, graph.m_adjacency[1][2])
        self.assertEqual(0, graph.m_adjacency[2][1])
        graph.AddEdge(1, 2)
        self.assertEqual(1, graph.m_adjacency[1][2])
        self.assertEqual(0, graph.m_adjacency[2][1])

        self.assertEqual(0, graph.m_adjacency[0][0])
        graph.AddEdge(0, 0)
        self.assertEqual(1, graph.m_adjacency[0][0])

    def test_Directed_IsEdge(self):
        graph: DirectedGraph = DirectedGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertFalse(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertFalse(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(1, 2)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertFalse(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(2, 1)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(0, 0)
        self.assertTrue(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

    def test_Directed_RemoveEdge(self):
        graph: DirectedGraph = DirectedGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertFalse(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertFalse(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(1, 2)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertFalse(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(2, 1)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))
        graph.AddEdge(0, 0)
        self.assertTrue(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

        graph.RemoveEdge(0, 0)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

        graph.RemoveEdge(1, 0)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertTrue(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

        graph.RemoveEdge(2, 1)
        self.assertFalse(graph.IsEdge(0, 0))
        self.assertFalse(graph.IsEdge(0, 1))
        self.assertFalse(graph.IsEdge(0, 2))
        self.assertFalse(graph.IsEdge(1, 0))
        self.assertFalse(graph.IsEdge(1, 1))
        self.assertTrue(graph.IsEdge(1, 2))
        self.assertFalse(graph.IsEdge(2, 0))
        self.assertFalse(graph.IsEdge(2, 1))
        self.assertFalse(graph.IsEdge(2, 2))

    def test_Directed_is_cycle_same_vertex(self):
        graph: DirectedGraph = DirectedGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(0, 1)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(1, 2)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(1, 1)
        self.assertTrue(graph.is_cyclic())

    def test_Directed_is_cycle_small_circle(self):
        graph: DirectedGraph = DirectedGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(0, 1)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(1, 2)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(1, 0)
        self.assertTrue(graph.is_cyclic())

    def test_Directed_is_cycle_big_circle(self):
        graph: DirectedGraph = DirectedGraph(3)
        graph.AddVertex(10)
        graph.AddVertex(11)
        graph.AddVertex(12)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(0, 1)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(1, 2)
        self.assertFalse(graph.is_cyclic())
        graph.AddEdge(2, 0)
        self.assertTrue(graph.is_cyclic())